---
- hosts: all
  become: yes

  tasks:
    - name: install python3 and nginx
      yum:
        name:
          - python3
          - python3-pip
          - nginx
        state: present

    - name: clone repo
      git:
        repo: 'https://github.com/saumitrapatil/sysad_intern.git'
        dest: /srv/checkout/ansible-nginx-gunicorn
        clone: yes
        update: yes

    - name: create virt env
      command:
        cmd: python -m venv /srv/checkout/ansible-nginx-gunicorn/venv
        creates: '/srv/checkout/ansible-nginx-gunicorn/venv'

    - name: install project dependencies
      pip:
        requirements: /srv/checkout/ansible-nginx-gunicorn/requirements.txt
        virtualenv: /srv/checkout/ansible-nginx-gunicorn/venv

    - name: run gunicorn
      gunicorn:
        app: 'sysad_intern.wsgi'
        chdir: '/srv/checkout/ansible-nginx-gunicorn'
        config: '/srv/checkout/ansible-nginx-gunicorn/gunicorn.conf.py'
        venv: '/srv/checkout/ansible-nginx-gunicorn/venv'

    - name: test gunicorn
      command: curl 'http://localhost:8000/about'
      register: test

    - debug: msg="{{ test.stdout }}"
