---
- hosts: aws_ec2
  gather_facts: no
  become: yes
  remote_user: ec2-user

  tasks:
    - name: install python3 and nginx
      yum:
        name:
          - git
          - python3
          - python3-pip
          - nginx
        state: present

    - name: clone repo
      git:
        repo: 'https://github.com/saumitrapatil/sysad_intern.git'
        dest: /srv/checkout/ansible-nginx-gunicorn
        clone: yes
        update: yes

    - name: create virt env
      command:
        chdir: /srv/checkout/ansible-nginx-gunicorn/
        cmd: python3 -m venv venv
        creates: /srv/checkout/ansible-nginx-gunicorn/venv

    - name: install project dependencies
      pip:
        requirements: /srv/checkout/ansible-nginx-gunicorn/requirements.txt
        virtualenv: /srv/checkout/ansible-nginx-gunicorn/venv

    - name: create nginx sites-enabled folder
      command:
        cmd: mkdir /etc/nginx/sites-enabled
        creates: /etc/nginx/sites-enabled

    - name: add conf to sites-enabled
      lineinfile:
        path: /etc/nginx/nginx.conf
        insertafter: '^    include /etc/nginx/conf.d/\*.conf;$'
        line: '    include /etc/nginx/sites-enabled/*.conf;'

    - name: Add nginx config
      template:
        src: ./templates/gunicorn-nginx.conf.j2
        dest: /etc/nginx/sites-enabled/gunicorn-nginx.conf

    - name: Add gunicorn service
      template:
        src: ./templates/gunicorn-ansible.service.j2
        dest: /etc/systemd/system/gunicorn-ansible.service

    - name: Start gunicorn
      systemd_service:
        name: gunicorn-ansible.service
        state: reloaded

    - name: Start nginx 
      systemd_service:
        name: nginx.service
        state: reloaded
